import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationMenuDemo } from "@/components/Header";
<<<<<<< HEAD
=======
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
>>>>>>> 3196891116969e000d1cb9e668d11e9f5ebc6d95
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          
          <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

              <SidebarProvider>
              <NavigationMenuDemo/>
<<<<<<< HEAD
           {children}
=======
                 <SidebarTrigger />
           {children}
              </SidebarProvider>
>>>>>>> 3196891116969e000d1cb9e668d11e9f5ebc6d95
          </ThemeProvider>
      </body>
    </html>
  );
}
